### ISSUE TITLE
USER STORY <Check-out multiple items>

### ISSUE THREAD

**Issue by 1234Christina** [1234Christina/agile1-ctina#2]
In order to **check-out multiple items in one click** as a **user** I can **add items to a shopping cart**
### Acceptance Criteria:
+ **Acceptance Criteria 1:** Add an item to the shopping cart
+ **Acceptance Criteria 2:** See the current items in the cart
+ **Acceptance Criteria 3:** Add further items to the cart
+ **Acceptance Criteria 4:** Remove an item from the cart
### Tasks:
- [ ] Task 1: Create the empty cart
- [ ] Task 2: Create feature to add item to cart
- [ ] Task 3: Show cart items on screen
- [ ] Task 4: Create feature to remove item from cart
